#define LOWEST                           1
#define TILDE                            2
#define TAGLIST                          3
#define QUOTE                            4
#define COLON                            5
#define MINUS                            6
#define NUMBER                           7
#define STOPWORD                         8
#define TERMLIST                         9
#define PREFIX                          10
#define PERCENT                         11
#define OR                              12
#define ORX                             13
#define AND                             14
#define LP                              15
#define RP                              16
#define TERM                            17
#define ATTRIBUTE                       18
#define MODIFIER                        19
#define ARROW                           20
#define STAR                            21
#define SEMICOLON                       22
#define LB                              23
#define RB                              24
#define LSQB                            25
#define RSQB                            26
